### ISSUE TITLE
Not finding images

### ISSUE THREAD

**Issue by Snapisch** [nv-tlabs/GET3D#73]
I am getting the following error and guess it is because I somehow have the wrong file path. I already tried pretty much all combinations, so maybe you can help me with the correct path name.

Creating output directory...
Launching processes...
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "filtered_lrelu_plugin"... Done.
Loading training set...
==> use shapenet dataset
==> use shapenet folder number 0
==> use image path: input/relief_data_rendered/img, num images: 0
Traceback (most recent call last):
  File "train_3d.py", line 330, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/jumo261b/.conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/jumo261b/.conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/jumo261b/.conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jumo261b/.conda/envs/get3d/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "train_3d.py", line 324, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 49, in subprocess_fn
    training_loop_3d.training_loop(rank=rank, **c)
  File "/home/h3/jumo261b/GET3D/training/training_loop_3d.py", line 134, in training_loop
    training_set_sampler = misc.InfiniteSampler(
  File "/home/h3/jumo261b/GET3D/torch_utils/misc.py", line 120, in __init__
    assert len(dataset) > 0
AssertionError

Used command:
python train_3d.py --outdir=log --data=input/relief_data_rendered/img --camera_path input/relief_data_rendered/camera --gpus=1 --batch=32 --gamma=40 --data_camera_mode shapenet_car  --dmtet_scale 1.0  --use_shapenet_split 1  --one_3d_generator 1  --fp32 0

Project structure:
input
-relief_data_rendered
--img
---Version1
----deva-capitoline-wolf-bas-Romania
-----000.png
-----...

**Comment by SteveJunGao** [comment]
Hi @Snapisch ,

According to your folder structure, you need to set  `--data=input/relief_data_rendered/img/Version1` and ` --camera_path =input/relief_data_rendered/camera`, let me know if this works or not ;) !

**Comment by Dandelionym** [comment]
Hi, Snapisch.

@Snapisch  Have you solved this problem?

**Comment by Snapisch** [comment]
Hello,

thanks for reminding me. My problem was caused by not properly configuring the files in 3dgan_data_split, since I did not use the shapenet dataset. Now everything is working properly. But thanks for your help ^^
